
networks:
  blog-networks:
    driver: bridge
services:

  db:
    image: postgres
    container_name: blogapplication-db-1
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blogDBPassword
      POSTGRES_DB: blog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - blog-networks
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  blog:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blog?autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=blog
      - SPRING_DATASOURCE_PASSWORD=blogDBPassword
      - SEND_MAIL_USERNAME=03anirudh2001@gmail.com
      - SEND_MAIL_PASSWORD=vjrf bwqz fnml lzha
    depends_on:
      db:
        condition: service_healthy
    # restart: always
    networks:
      - blog-networks


volumes:
  postgres-data: {}


    
